HazelcastWebUI/Models/ErrorViewModel.cs
namespace HazelcastWebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HazelcastWebUI/Controllers/CityController.cs
using Cache.Services;
using Microsoft.AspNetCore.Mvc;

namespace HazelcastWebUI.Controllers
{
    public sealed class CityController : Controller
    {
        private readonly ICitiesService _citiesService;

        public CityController(ICitiesService citiesService)
        {
            _citiesService = citiesService;
        }

        public async Task<IActionResult> Cities(CancellationToken token = default)
        {
            try
            {
                var cityList = await _citiesService.LoadCitiesAsync(token).ConfigureAwait(false);
                return View(cityList);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public async Task<IActionResult> Populations(CancellationToken token = default)
        {
            try
            {
                var cityList = await _citiesService.LoadCitiesWithPopulationAsync(token).ConfigureAwait(false);
                return View(cityList);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public async Task<IActionResult> Areas(CancellationToken token = default)
        {
            try
            {
                var cityList = await _citiesService.LoadCitiesWithPopulationAreaAsync(token).ConfigureAwait(false);
                return View(cityList);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public async Task<IActionResult> Mayors(CancellationToken token = default)
        {
            try
            {
                var cityList = await _citiesService.LoadCitiesWithPopulationAreaMayorAsync(token).ConfigureAwait(false);
                return View(cityList);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public async Task<IActionResult> CitiesDetails(CancellationToken token = default)
        {
            try
            {
                var cityList = await _citiesService.LoadCitiesWithPopulationAreaMayorCountryAsync(token).ConfigureAwait(false);
                return View(cityList);
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

HazelcastWebUI/Controllers/CountryController.cs
using Cache.Services;
using Microsoft.AspNetCore.Mvc;

namespace HazelcastWebUI.Controllers
{
    public sealed class CountryController : Controller
    {
        private readonly ICountriesService _countriesService;

        public CountryController(ICountriesService countriesService)
        {
            _countriesService = countriesService;
        }

        public async Task<IActionResult> Countries()
        {
            var countries = await _countriesService.LoadCountriesAsync().ConfigureAwait(false);
            return View(countries);
        }
    }
}

HazelcastWebUI/Controllers/HomeController.cs
using HazelcastWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HazelcastWebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HazelcastWebUI/Views/City/Areas.cshtml
@model IEnumerable<Model.CityWithPopulationArea>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">City</th>
            <th scope="col">Country</th>
            <th scope="col">Population</th>
            <th scope="col">Area</th>

        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@i</th>
                <td>@item.CityName</td>
                <td>@item.CountryName</td>
                <td>@item.Population</td>
                <td>@item.Area km²</td>
            </tr>
            i++;
        }
    </tbody>
</table>

HazelcastWebUI/Views/City/Cities.cshtml
@model IEnumerable<Model.City>
@{
    ViewData["Title"] = "Cities";
}
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">City</th>
            <th scope="col">Country</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@i</th>
                <td>@item.CityName</td>
                <td>@item.CountryName</td>
            </tr>
            i++;
        }
    </tbody>
</table>

HazelcastWebUI/Views/City/CitiesDetails.cshtml
@model IEnumerable<Model.CityWithPopulationAreaMayorCountry>
@{
    ViewData["Title"] = "Mayors";
}
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">City</th>
            <th scope="col">City Population</th>
            <th scope="col">City Area</th>
            <th scope="col">Mayor</th>
            <th scope="col">Elected Year</th>
            <th scope="col">Country</th>
            <th scope="col">Dialing Code</th>
            <th scope="col">Prime Minister</th>
            <th scope="col">Currency</th>
            <th scope="col">Country Population</th>
            <th scope="col">Official Language</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@i</th>
                <td>@item.CityName</td>
                <td>@item.CityPopulation</td>
                <td>@item.CityArea km²</td>
                <td>@item.MayorName</td>
                <td>@item.ElectedYear</td>
                <td>@item.CountryName</td>
                <td>@item.DialingCode</td>
                <td>@item.PrimeMinister</td>
                <td>@item.Currency</td>
                <td>@item.CountryPopulation M</td>
                <td>@item.OfficialLanguage</td>
            </tr>
            i++;
        }
    </tbody>
</table>

HazelcastWebUI/Views/City/Mayors.cshtml
@model IEnumerable<Model.CityWithPopulationAreaMayor>
@{
    ViewData["Title"] = "Mayors";
}
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">City</th>
            <th scope="col">Country</th>
            <th scope="col">Population</th>
            <th scope="col">Area</th>
            <th scope="col">Mayor</th>
            <th scope="col">Year</th>

        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@i</th>
                <td>@item.CityName</td>
                <td>@item.CountryName</td>
                <td>@item.Population</td>
                <td>@item.Area km²</td>
                <td>@item.MayorName</td>
                <td>@item.ElectedYear</td>
            </tr>
            i++;
        }
    </tbody>
</table>

HazelcastWebUI/Views/City/Populations.cshtml
@model IEnumerable<Model.CityWithPopulation>
@{
    ViewData["Title"] = "Populations";
}
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">City</th>
            <th scope="col">Country</th>
            <th scope="col">Population</th>
            
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@i</th>
                <td>@item.CityName</td>
                <td>@item.CountryName</td>
                <td>@item.Population</td>
            </tr>
            i++;
        }
    </tbody>
</table>

HazelcastWebUI/Views/Country/Countries.cshtml
@model IEnumerable<Model.Country>
@{
    ViewData["Title"] = "Countries";
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Country</th>
            <th scope="col">Dialing Code</th>
            <th scope="col">Prime Minister</th>
            <th scope="col">Currency</th>
            <th scope="col">Population</th>
            <th scope="col">Official Language</th>

        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@i</th>
                <td>@item.CountryName</td>
                <td>@item.DialingCode</td>
                <td>@item.PrimeMinister</td>
                <td>@item.Currency</td>
                <td>@item.Population</td>
                <td>@item.OfficialLanguage</td>
            </tr>
            i++;
        }
    </tbody>
</table>

HazelcastWebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HazelcastWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HazelcastWebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HazelcastWebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HazelcastWebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Cities">Cities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="CitiesDetails">Cities Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Populations">Populations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Areas">Areas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Mayors">Mayors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Countries">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HazelcastWebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>